### ISSUE TITLE
Crash occurs when long pressed on a folder in storage

### ISSUE THREAD

**Issue by Godwyyn** [kollerlukas/Camera-Roll-Android-App#172] opened 2018-04-04 23:18 UTC
#### Expected behavior
When I navigate to a storage folder using the "File Explorer" option, I expected the app to highlight the storage folder, or do nothing when I click and hold or long press on the folder.

#### Actual behavior
When I click and hold on any folder at the storage location,the app crashes and returns to the Home Activity.

#### How to reproduce
- Download the Camera Roll App from Playstore
- Launch the App
- At the home activity, Click on the menu option icon at the top right
- From the menu options click on "File Explorer"
- Navigate to a folder 
- Long press or click and hold on the folder or any sub-folder
- The app crashes and returns to the Home Activity.

* Browser: Version 1.0.5
* Operating system: Infinix Hot, Android Kitkat

#### Recording Of The Bug
https://www.youtube.com/watch?v=GUkrQfujG6k
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@godwyn/crash-occurs-when-long-pressed-on-a-folder-in-storage">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by y0umu** [comment] 2018-04-05 02:55
Plain weired. I cannot reproduce it following your procedure. I have Camera Roll v1.0.5 installed on Android 7.0 (MIUI Global 8.3.29).

**Comment by Godwyyn** [comment] 2018-04-05 04:23
Try doing that with Android 4.4 version

**Comment by kollerlukas** [comment] 2018-04-05 09:03
This was already fixed with this commit 465eb6be7c189533ba344ad4b104bc26e46b5992

**Closed by kollerlukas** 2018-04-05 09:03 UTC
